# Generated by Django 6.0.2 on 2026-03-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='moral',
            new_name='Description',
        ),
    ]
