# Generated by Django 6.0.2 on 2026-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_save_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
