# Generated by Django 6.0.2 on 2026-03-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_borrowed_b_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='id',
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='b_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
