# Generated by Django 6.0.2 on 2026-03-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_borrowed_id_alter_borrowed_b_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='i_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
