# Generated by Django 6.0.3 on 2026-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_borrowed_book_id_alter_borrowed_i_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
