# Generated by Django 6.0.3 on 2026-09-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='manager.member')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('member', 'month')},
            },
        ),
    ]
