# Generated by Django 6.0.3 on 2026-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_membershipfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
