# Generated by Django 6.0.3 on 2026-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_borrowed_borrow_date_borrowed_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='seen_by_member',
            field=models.BooleanField(default=False),
        ),
    ]
