# Generated by Django 6.0.2 on 2026-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=100)),
                ('p_date', models.DateTimeField()),
                ('moral', models.CharField(max_length=1000)),
                ('Quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
