# Generated by Django 6.0.2 on 2026-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_moral_save_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
