# Generated by Django 6.0.2 on 2026-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='Category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
