# Generated by Django 6.0.2 on 2026-03-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
