# Generated by Django 6.0.2 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='Book',
            field=models.CharField(default='', max_length=50),
        ),
    ]
