# Generated by Django 6.0.2 on 2026-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_borrowed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='b_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
