# Generated by Django 6.0.2 on 2026-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_borrowed_i_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='book_id',
            field=models.CharField(default=0),
        ),
    ]
