# Generated by Django 6.0.2 on 2026-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_borrowed_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='i_id',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
